async function generateResult() {
  const result = document.getElementById("result");
  const name = document.getElementById("nameInput").value || "Sunless";
  const container = document.querySelector(".container");
  const title = document.querySelector("h2");
  const input = document.getElementById("nameInput");
  const button = document.getElementById("generate");

  // Disable button
  button.disabled = true;
  button.style.pointerEvents = "none";

  // Fade everything out
  title.classList.add("fade-out");
  input.classList.add("fade-out");
  button.classList.add("fade-out");
  container.classList.add("centered");

  await new Promise(resolve => setTimeout(resolve, 800));

  // Hide them completely
  title.style.display = "none";
  input.style.display = "none";
  button.style.display = "none";

  // Wake-up message
  const wakeUpText = document.createElement("p");
  wakeUpText.textContent = `[Wake up, ${name}! Your nightmare is over.]`;
  wakeUpText.classList.add("glow-text");
  wakeUpText.style.fontSize = "2.0rem"
  container.appendChild(wakeUpText);

  // Keep message for a moment
  await new Promise(resolve => setTimeout(resolve, 2000));

  // Fade out the message
  wakeUpText.classList.add("fade-out");
  await new Promise(resolve => setTimeout(resolve, 800));
  wakeUpText.remove();

  // Move container back up

  await new Promise(resolve => setTimeout(resolve, 800));

  // Prepare result card
  result.innerHTML = ``;
  result.classList.remove("hidden");
  result.classList.add("visible");

const TrueNames = [
"Lost from Light",
"Changing Star",
"Song of the Fallen",
"Raised by Wolves",
"Nightingale",
"Promise of a Distant Sky",
"Sky Tide",
"Whispering Blade",
"Wake of Ruin",
"Summer Knight",
"Not so Funny Anymore",
"Shield Wall",
"Lightslayer",
"Death Singer",
"Dream Merchant",
"Ravensong",
"Ash Between Stars",
"Keeper of Forgotten Oaths",
"Thorn of Tomorrow",
"Echo of the Endless Sea",
"Bearer of Silent Flames",
"Grave of Promises",
"Child of the Pale Moon",
"Whisper of the Abyss",
"Crown of Falling Leaves",
"Voice of the Stormbound",
"Scion of Dusk",
"Wanderer of Hollow Roads",
"Blade Without Shadow",
"Memory of the First Dawn",
"Heart of the Still Tide",
"Harbinger of Quiet Skies",
"Veil of the Unseen Sun",
"Watcher at the Edge",
"Flame That Forgot Its Name",
"Dream of the Broken World",
"Echo in the Glass",
"Child of Silent Horizons",
"Keeper of Crimson Dust",
"Wing of the Nameless Sky",
"Throne of Forgotten Kings",
"Whisper Beneath the Waves",
"Star That Never Set",
"Shade of the Silver Bloom",
"Voice Beneath the Ashes",
"Bearer of the Last Light",
"Heart of Winter’s Grace",
"Singer of Hollow Stars",
"Watcher of the Waning Flame",
"Ender of the Long Night",
"Heir to the Silent Depths",
"Candle in the Deep",
"Silent Requiem",
"Broken Halo",
"Crimson Dusk",
"Glass Serpent",
"Fallen Echo",
"Whispered Dawn",
"Hidden Thorn",
"Last Ember",
"Golden Mirage",
"Raven’s Call",
"Silver Veil",
"Shattered Crown",
"Frozen Hymn",
"Moon’s Lament",
"Burning Oath",
"Echoed Truth",
"Fading Star",
"Twilight Bloom",
"Nameless Wing",
"Lonely Tide",
"Graven Light",
"Black Petal",
"Azure Wound",
"Bleeding Sky",
"Silent Ashes",
"Forgotten Grace",
"Eternal Mirage",
"Thorned Memory",
"Hidden Flame",
"Last Horizon",
"Echo of Dusk",
"Song of Ash",
"Flame of Dawn",
"Crown of Thorns",
"Voice of Silence",
"Heart of Frost",
"Shadow of Faith",
"Wing of Glass",
"Tears of Ember",
"Breath of Storms",
"Blade of Mercy",
"Call of Ruin",
"Whisper of Night",
"Light of Sorrow",
"Rise of Cinders",
"Path of Echoes",
"End of Dreams",
"Fall of Stars",
"Touch of Winter",
"Mark of Silence",
"Whisper of Dawn",
"Flame of Silence",
"Crown of Dust",
"Child of Storms",
"Echo of Winter",
"Blade of Shadows",
"Song of Thorns",
"Heart of Cinders",
"Voice of Ruin",
"Wing of Ashes",
"Thorn of Twilight",
"Star of Sorrow",
"Light of Frost",
"Dream of Glass",
"Shade of Harmony",
"Soul of Iron",
"Gift of Silence",
"Fang of the Fallen",
"Call of Midnight",
"Scar of Eternity",
"Prince of Echoes",
"Warden of Ash",
"Hand of the Abyss",
"Eyes of the Forgotten",
"Herald of Stars",
"Child of Dusk",
"Throne of Silence",
"Heart of the Abyss",
"Son of Storms",
"Witch of Glass",
"Silent Crow",
"Silver Fang",
"Black Sun",
"Broken Halo",
"Fallen Star",
"Twilight Warden",
"Crimson Wolf",
"Glass Saint",
"Night Whisper",
"Gravekeeper",
"Starborn",
"Ashwalker",
"Moonbreaker",
"Stormhand",
"Dreamweaver",
"Runebinder",
"Frost King",
"Veilstrider",
"Firethorn",
"Stoneheart",
"Nightbloom",
"Skydancer",
"Bloodhound",
"Brightfang",
"Shadecaller",
"Windreaver",
"Spellbound",
"Voidrunner",
"Bladeseeker",
"Dawnchaser",
"Soulmender",
"Nightreign",
"Flameshaper",
"Ironveil",
"Starwaker",
"Grimhand",
"Dustborne",
"Lightbringer",
"Stormborn",
"Dreambane",
"Whispering Night Blade",
"Crimson Moon Saint",
"Fallen Star King",
"Silent Ash Wanderer",
"Broken Sky Herald",
"Twilight Flame Warden",
"Golden Thorn Seeker",
"Silver Wing Nomad",
"Shadowborn Dream Weaver",
"Burning Crown Keeper",
"Frozen Heart Saint",
"Bleeding Sun Warrior",
"Midnight Glass Hunter",
"Hidden Dawn Slayer",
"Shattered Halo Knight",
"Raven Wing Herald",
"Stormbound Grave Watcher",
"Echoed Flame Monk",
"Lone Star Wanderer",
"Veiled Light Sage",
"Cinder Bloom Witch",
"Hollow Dream King",
"Azure Thorn Priest",
"Endless Sky Vagabond",
"Grim Frost Captain",
"Brightfang Storm Hunter",
"Dustveil Flamebearer",
"Moonlit Path Seeker",
"Silent Frostblade",
"Black Sun Prophet",
"the provoker",
]
const Flaws = [
  { name: "impulsive talk", desc: " You cannot stop talking and you cannot hide what you are thinking" },
  { name: "Crimson Decay", desc: "Your body weakens each time you shed blood." },
  { name: "Soul Rot", desc: "Your spirit erodes with every use of power." },
  { name: "Glass Bones", desc: "Each injury leaves you more fragile than before." },
  { name: "essence Fever", desc: "Prolonged essence use burns your life force." },
  { name: "Echo Burn", desc: "Your reflections and echoes drain your vitality." },
  { name: "Bound Tongue", desc: "You cannot speak falsehoods or secrets." },
  { name: "Silent Path", desc: "Your presence prevents you from casting in motion." },
  { name: "Crippled Flow", desc: "Certain elements reject your essence entirely." },
  { name: "Iron Oath", desc: "You are bound to keep any promise spoken aloud." },
  { name: "Shattered Focus", desc: "You lose control if you channel essence for too long." },
  { name: "Dread Aura", desc: "Your presence spreads unease to everyone nearby." },
  { name: "Leeching Shadow", desc: "Your aura slowly drains others’ vitality." },
  { name: "Echo of Misfortune", desc: "Disasters tend to befall those close to you." },
  { name: "Cursed Breath", desc: "Your emotions twist the minds of nearby beings." },
  { name: "Wailing Spirit", desc: "When you sleep, others nearby hear your screams." },
  { name: "Bloodrush", desc: "The scent of battle drives you into violent frenzy." },
  { name: "Unchained Desire", desc: "You struggle to resist temptation or thrill." },
  { name: "Rage Veil", desc: "Anger clouds your reason when wounded." },
  { name: "Shadow Hunger", desc: "You crave power whenever you sense weakness." },
  { name: "Echoed Pride", desc: "Praise blinds you to flaws and danger." },
  { name: "Echo Heart", desc: "You feel emotions that aren’t yours." },
  { name: "Fading Name", desc: "People forget you too easily." },
  { name: "Mirror Hunger", desc: "You mimic what you see, without meaning to." },
  { name: "Shattered Will", desc: "You hesitate when facing yourself." },
  { name: "Hollow Gaze", desc: "You see nothing where others see light." },
  { name: "Silent Step", desc: "Your presence leaves no trace, even when you wish it did." },
  { name: "Bound Memory", desc: "You relive a single moment each night." },
  { name: "Flickering Form", desc: "Your shape falters when emotions rise." },
  { name: "Frayed Thread", desc: "Your existence feels unstable around strong wills." },
  { name: "Still Breath", desc: "Your body forgets to move when calm." },
  { name: "Draining Calm", desc: "Your peace saps energy from those nearby." },
  { name: "Weeping Light", desc: "Sources of light dim near you." },
  { name: "Murmuring Shade", desc: "Whispers echo from your shadow." },
  { name: "Grim Reflection", desc: "Your reflection shows who you might become." },
  { name: "Bleeding Silence", desc: "Sound dies when you feel fear." },

  { name: "Chained Instinct", desc: "You act before thinking under stress." },
  { name: "Unbound Echo", desc: "Your thoughts sometimes speak aloud." },
  { name: "Feral Calm", desc: "The quieter it gets, the more violent you feel." },
  { name: "Craving Form", desc: "You envy those with solid bodies." },
  { name: "Yearning Void", desc: "You hate emptiness but seek it still." },
  { name: "Pale Sleep", desc: "You wake feeling more tired than before." },
{ name: "Glass Bones", desc: "Your body cracks too easily." },
{ name: "Heavy Breath", desc: "Air feels thicker each day." },
{ name: "Blurred Sight", desc: "Your vision flickers in dim light." },
{ name: "Faint Pulse", desc: "Your heartbeat skips without reason." },
{ name: "Wandering Mind", desc: "You forget why you began something." },
{ name: "Shaking Grip", desc: "Your hands tremble when still." },
{ name: "Split Thought", desc: "You hear your own mind argue back." },
{ name: "Cold Blood", desc: "You never feel warmth, no matter the fire." },
{ name: "Sun Fragile", desc: "Direct light burns your skin faintly." },
{ name: "Weak Echo", desc: "Your voice sounds hollow to you." },
{ name: "Crimson Tears", desc: "Your eyes bleed when you feel pain." },
{ name: "Lost Sense", desc: "You can’t feel texture or temperature." },
{ name: "Silent Panic", desc: "Your body freezes when danger nears." },
{ name: "Drifting Thought", desc: "You fade into daydreams too easily." },
{ name: "Burned Scent", desc: "You can’t smell anything anymore." },
{ name: "Hollow Hunger", desc: "No meal feels enough." },
{ name: "Soft Bones", desc: "You move carefully to avoid breaking." },
{ name: "Twitching Eye", desc: "Your gaze jerks when you lie." },
{ name: "Restless Shadow", desc: "Your shadow moves when you don’t." },
{ name: "Ash Breath", desc: "Each exhale feels heavy and dry." },
{ name: "Frost Nerve", desc: "Cold crawls under your skin often." },
{ name: "Empty Stomach", desc: "You forget to eat for days." },
{ name: "Ghost Limb", desc: "You feel pain from something you lost." },
{ name: "Tired Soul", desc: "You fall asleep at strange times." },
{ name: "Crooked Step", desc: "Your legs don’t move evenly." },
{ name: "Echo Pain", desc: "You feel others’ wounds faintly." },
{ name: "Dry Eyes", desc: "Blinking burns, crying hurts." },
{ name: "Broken Voice", desc: "Speech costs you effort." },
{ name: "Coughing Dust", desc: "You taste dirt when you breathe deep." },
{ name: "Dim Smile", desc: "Joy feels unfamiliar." },
{ name: "Cracked Nail", desc: "Even small strain leaves marks." },
{ name: "Feeble Grip", desc: "You drop things often." },
{ name: "Sleep Murmur", desc: "You whisper secrets in your sleep." },
{ name: "Twisting Gut", desc: "Pain comes and goes without cause." },
{ name: "Sun Spots", desc: "Your skin stains under light." },
{ name: "Brittle Nerve", desc: "Pain lingers longer than it should." },
{ name: "Weary Sight", desc: "You see faint outlines that vanish." },
{ name: "Lost Tune", desc: "You can’t remember songs you knew." },
{ name: "Hollow Taste", desc: "Food feels like dust in your mouth." },
{ name: "Uneven Heart", desc: "Beats sometimes stop for a moment." },
{ name: "Slow Blood", desc: "Wounds take too long to close." },
{ name: "Numb Skin", desc: "Touch feels distant and dull." },
{ name: "Blistered Palm", desc: "Your hands ache after holding anything." },
{ name: "Split Dream", desc: "You dream twice each night." },
{ name: "Low Fever", desc: "You’re always slightly warm." },
{ name: "Heavy Tongue", desc: "Words stumble out slowly." },
{ name: "Weak Gaze", desc: "Your stare never meets another’s long." },
{ name: "Dust Cough", desc: "Your breath sounds dry and rough." },
{ name: "Bending Spine", desc: "You can’t stand straight for long." },
{ name: "Sun’s Bane", desc: "Sunlight burns your essence." },
{ name: "Frozen Core", desc: "Heat weakens your essence flow." },
{ name: "Still Air", desc: "Your essence won’t move without wind." },
{ name: "Blood Hunger", desc: "Your essence fades away from life." },
{ name: "Lunar Dependency", desc: "Your essence weakens without moonlight." },
{ name: "Echo of Shadows", desc: "No shadow means no essence control." },
{ name: "Flickering Flame", desc: "Calm mind kills your essence." },
{ name: "Numb Frost", desc: "Your emotions freeze with your essence." },
{ name: "Silent Ground", desc: "You lose essence when off natural ground." },
{ name: "Empty Sky", desc: "Clear skies drain your essence fast." },
{ name: "Vein Erosion", desc: "Using power tears your body apart." },
{ name: "Spectral Anchor", desc: "Away from your mark, essence thins." },
{ name: "Withered Heart", desc: "Each spell burns your life force." },
{ name: "Cracked Soul", desc: "Your essence whispers against you." },
{ name: "Twilight Veil", desc: "Too much light or dark weakens you." },
{ name: "Rotting Breath", desc: "Clean air rots your body." },
{ name: "Eclipsed Form", desc: "Only strong under eclipses." },
{ name: "Hollow Pulse", desc: "If your heart slows, your essence stop." },
{ name: "Earthbound", desc: "You lose strength off the ground." },
{ name: "Shattered Reflection", desc: "Reflections scatter your essence." },
{ name: "Clear Conscience", desc: "You can’t lie." },
{ name: "Gentle Hand", desc: "You can’t kill any living being." },
{ name: "Silent Tongue", desc: "You can’t speak your true thoughts." },
{ name: "Restless Mind", desc: "You can’t sleep naturally." },
{ name: "Broken Trust", desc: "You can’t form contracts or vows." },
{ name: "Still Heart", desc: "You can’t feel anger." },
{ name: "Eternal Guilt", desc: "You can’t forgive yourself." },
{ name: "Muted Cry", desc: "You can’t call for help." },
{ name: "Faithless Soul", desc: "You can’t pray or believe in anything." },
{ name: "Wandering Dream", desc: "You can’t dream anymore." },
{ name: "Bound Mercy", desc: "You can’t harm the weak." },
{ name: "Silver Tongue", desc: "You can’t tell the full truth." },
{ name: "Dead Sleep", desc: "You can’t wake without pain." },
{ name: "Unfed Hunger", desc: "You can’t feel full or satisfied." },
{ name: "Fallen Word", desc: "You can’t speak your own name." },
{ name: "Trembling Soul", desc: "You can’t face your reflection." },
{ name: "Hollow Step", desc: "You can’t walk on sacred ground." },
{ name: "Caged Breath", desc: "You can’t breathe freely under the open sky." },
{ name: "Silent Oath", desc: "You can’t refuse a promise once spoken." },
{ name: "Frozen Tear", desc: "You can’t cry, no matter the pain." },
{ name: "Blind Faith", desc: "You can’t doubt what you believe." },
{ name: "Feral Will", desc: "You can’t stop once you start fighting." },
{ name: "Bound Path", desc: "You can’t walk the same road twice." },
{ name: "Wordbound", desc: "You can’t break your spoken word." },
{ name: "Hollow Stomach", desc: "You can’t taste food." },
{ name: "Mute Spirit", desc: "You can’t cast without whispering first." },
{ name: "Cursed Kindness", desc: "You can’t ignore a plea for help." },
{ name: "Fading Memory", desc: "You can’t remember faces for long." },
{ name: "Ash Step", desc: "You can’t walk through fire or ash." },
{ name: "Silent Heart", desc: "You can’t love again." },
{ name: "Tethered Will", desc: "You can’t disobey direct commands." },
{ name: "Faith Chain", desc: "You can’t act against your belief." },
{ name: "Waning Voice", desc: "You can’t speak after sunset." },
{ name: "Mirror Fear", desc: "You can’t face your reflection." },
{ name: "Frost Breath", desc: "You can’t exhale warmth." },
{ name: "Dim Sight", desc: "You can’t see light brighter than a candle." },
{ name: "Wanderer's Curse", desc: "You can’t stay in one place for long." },
{ name: "Shadow Promise", desc: "You can’t lie under moonlight." },
{ name: "Bitter Truth", desc: "You can’t tell lies, even to yourself." },
{ name: "Caged Flame", desc: "You can’t control your essence in anger." },
{ name: "Veiled Soul", desc: "You can’t reveal your true form." },
{ name: "Solemn Step", desc: "You can’t run." },
{ name: "Empty Tongue", desc: "You can’t speak any spell twice." },
{ name: "Faith Echo", desc: "You can’t deny another’s belief." },
{ name: "Dream Tether", desc: "You can’t wake others from sleep." },
{ name: "Wounded Voice", desc: "You can’t sing or chant spells." },
{ name: "Crimson Gaze", desc: "You can’t look at blood without trembling." },
{ name: "Shattered Oath", desc: "You can’t make promises anymore." },
{ name: "Cursed Breath", desc: "You can’t breathe in holy air." },
{ name: "Silent Will", desc: "You can’t resist mental control." },
{ name: "Dying Word", desc: "You can’t speak when wounded." },
{ name: "Bending Spine", desc: "You can’t stand straight for long." },
{ name: "Shaking Hand", desc: "Your hands tremble when you focus." },
{ name: "Weak Knees", desc: "Your legs give out under pressure." },
{ name: "Clouded Eye", desc: "You see shapes, not details." },
{ name: "Faint Heart", desc: "Your chest burns after exertion." },
{ name: "Scarred Throat", desc: "Speaking hurts your voice." },
{ name: "Frozen Fingers", desc: "Your hands feel no warmth." },
{ name: "Cracked Foot", desc: "Each step sends pain through your leg." },
{ name: "Split Ear", desc: "Your hearing fades on one side." },
{ name: "Tired Blood", desc: "You tire quickly no matter your strength." },
{ name: "Burned Skin", desc: "Your flesh reacts to heat and light." },
{ name: "Crooked Back", desc: "You move with a painful hunch." },
{ name: "Blind Spot", desc: "There’s a patch of darkness in your sight." },
{ name: "Slow Pulse", desc: "Your body reacts late to danger." },
{ name: "Heavy Arm", desc: "Your dominant arm is sluggish and weak." },
{ name: "Fragile Bone", desc: "Hard hits can easily break you." },
{ name: "Scarred Face", desc: "Your left eye closes on its own." },
{ name: "Breathless", desc: "Running steals your air instantly." },
{ name: "Tremor Step", desc: "You stumble without warning." },
{ name: "Burnt Nerve", desc: "Pain flares when you channel essence." },
{ name: "Dull Taste", desc: "Food feels like ash in your mouth." },
{ name: "Weak Grip", desc: "You can’t hold weapons firmly." },
{ name: "Frost Skin", desc: "Cold locks your joints stiff." },
{ name: "Dim Hearing", desc: "You miss soft sounds and whispers." },
{ name: "Empty Lungs", desc: "You struggle to breathe deeply." },
{ name: "Sealed Mouth", desc: "You can’t open your jaw fully." },
{ name: "Heavy Blood", desc: "You bleed slowly but painfully." },
{ name: "Fading Sight", desc: "Your vision blurs after each battle." },
{ name: "Twisted Leg", desc: "You walk with a limp." },
{ name: "Stiff Neck", desc: "You can’t turn your head freely." },
{ name: "Crooked Fingers", desc: "You can’t make tight fists." },
{ name: "Ash Breath", desc: "You cough black dust when tired." },
{ name: "Faint Grip", desc: "Everything feels slippery in your hands." },
{ name: "Bone Rattle", desc: "Your joints ache with every move." },
{ name: "Torn Muscle", desc: "Fast movement rips at old wounds." },
{ name: "Dim Eye", desc: "You see poorly in bright light." },
{ name: "Hollow Stomach", desc: "You can’t keep food down." },
{ name: "Burn Scar", desc: "Your skin tightens with pain near fire." },
{ name: "Flickering Sight", desc: "Your vision fades in and out." },
{ name: "Stone Knee", desc: "You can’t kneel or bend easily." },
{ name: "Cracked Rib", desc: "Deep breaths stab your chest." },
{ name: "Cold Hands", desc: "Your touch feels lifeless and numb." },
{ name: "Locked Joint", desc: "Your shoulder freezes mid-motion." },
{ name: "Thin Skin", desc: "Even small cuts bleed too much." },
{ name: "Faint Voice", desc: "You can’t raise your tone." },
{ name: "Shattered Sense", desc: "You can’t feel heat or cold properly." },
{ name: "Dry Eyes", desc: "Blinking burns your sight." },
{ name: "Weak Spine", desc: "You can’t carry heavy loads." },
{ name: "Slowed Nerves", desc: "Your body reacts after your mind." },
{ name: "Shallow Breath", desc: "Cold air makes you choke." }


]
const Attributes = [
"Battle Master",
"Blessing",
"Blood Weave",
"Bone Weave",
"Child of Shadows",
"Complete Steel Body",
"Curse",
"Dark Destrier",
"Dragonslayer",
"Dreadlord",
"Dreamspawn",
"Dreamwalker",
"Ember of Divinity",
"Enthralled",
"Fated",
"Fateless",
"Flame of Divinity",
"Godheart",
"Greater Steel Body",
"Heart of Darkness",
"Jade Shell",
"Lesser Iron Body",
"Lord of Shadows",
"Lucky",
"Marble Shell",
"Mark of Ash",
"Mark of Death",
"Mark of Divinity",
"Mark of Shadows",
"Marvel",
"Master of Shadows",
"Nephilim",
"Poet",
"Ravenous",
"Shadow Guide",
"Shell",
"Soul Beast",
"Soul Companion",
"Soul Weapon",
"Soul Weave",
"Spark of Divinity",
"Spirit Guide",
"Swift",
"Swift Hand",
"The Fire",
"Essence Drinker",
"Silent Heart",
"Stormborn",
"Frostbound",
"Earthshaper",
"Voidwalker",
"Star Touched",
"Runeblood",
"Echoed Soul",
"Skystrider",
"Moonbound",
"Lightbearer",
"Heart of the Forge",
"Spiritforged",
"Flamebound",
"Ashborne",
"Twilight Warden",
"Veilbreaker",
"Shadowborn",
"Dreamchaser",
"Bloodforged",
"Spirit Vein",
"Essence Reaver",
"Gravebound",
"Mirage Walker",
"Dawnkeeper",
"Nightbloom",
"Stonehand",
"Flamebinder",
"Voice of Silence",
"Fatebreaker",
"Essence Eater",
"Boundless",
"Glass Vein",
"Starforged",
"Shatterborn",
"Death Whisper",
"Sunmarked",
"Moonmarked",
"Cinderheart",
"Faithforged",
"Stormwalker",
"Crimson Vow",
"Hollowborn",
"Mindweaver",
"Silverblood",
"Spectral Soul",
"Emberweaver",
"Lightforged",
"Flamehand",
"Stormcaller",
"Bonebound",
"Fatewoven",
"Spiritflame",
"Grimhand",
"Soulrender",
"Voidtouched",
"Echoborn",
"Fleshcarver",
"Mindflame",
"Starvein",
"Spiritbound",
"Essencewrought",
"Lightwoven",
"Blightborn",
"Bonechant",
"Crowmarked",
"Essencebound",
"Faithbound",
"Shadoweater",
"Heartpiercer",
"Skysworn",
"Blooded Oath",
"Essencetide",
"Stoneborn",
"Stormvein",
"Grimheart",
"Stormsoul",
"Glassheart",
"Runeborn",
"Spiritwoven",
"Nightreaver",
"Whisperborn",
"Essencebrand",
"Soulmarked",
"Dreamforged",
"Seabound",
"Rootwalker",
"Flamewrought",
"Sandshaper",
"Frostweaver",
"Dustforged",
"Mindbreaker",
"Essencelocked",
"Vowkeeper",
"Deathbound",
"Fleshmender",
"Spiritshard",
"Sunforged",
"Moonforged",
"Nightbound",
"Gravewalker",
"Essencechaser",
"Starcaller",
"Bloodveil",
"Faithwoven",
"Skyforged",
"Heartwoven",
"Flamecarved",
"Mindwoven",
"Fleshbound",
"Stormbringer",
"Spiritreaver",
"Essenceweaver",
"Bloodscar",
"Bonekeeper",
"Essencebloom",
"Dreamwoven",
"Frostreaver",
"Essenceshaper",
"Skybloom",
"Essencerender",
"Moonshadow",
"Twilightforged",
"Essencefang",
"Shadowhand",
"Fatewalker",
"Embervein",
"Essencetongue",
"Wraithborn",
"Gravemarked",
"Essencewalker",
"Essencecrowned",
"Rootforged",
"Essencechain",
"Glasswalker",
"Spiritmirror",
"Flameveil",
"Essenceflame",
"Fleshweaver",
"Spiritfang",
"Embercaller",
"Essencemender",
"Shadeforged",
"Lightbreaker",
"Essenceheart",
"Boneveil",
"Essencegazer",
"Soulflare",
"Dreammarked",
"Essencewarden",
"Bloodwoven",
"Essencereaver",
"Voidborn",
"Soulchain",
"Essenceborn",
"Graveforged",
"Faithbreaker",
"Windtouched",
"Essencehowler",
"Shadowroot",
"Spiritbane",
"Cinderblood",
"Blooddrinker",
"Moonbloom",
"Fatebound",
"Dreamstalker",
"Ashforged",
"Spiritdrift",
"Stoneheart",
"Lightshard",
"Essenceseer",
"Bloodthread",
"Skyfury",
"Frostfang",
"Essencekeeper",
"Boneweaver",
"Flamefang",
"Spiritborn",
"Essencefused",
"Voidbreaker",
"Echoheart",
"Essencebringer",
"Fleshsmith",
"Essenceflare",
"Stormheart",
"Dustwalker",
"Essencegrasp",
"Mindshadow",
"Faithflame",
"Essencegloom",
"Moonscar",
"Essencecurse",
"Dreambinder",
"Essencewraith",
"Ironvein",
"Essencestorm",
"Glassblood",
"Essencebender",
"Spiritshaper",
"Sunscar",
"Essenceharrow",
"Shadowbinder",
"Essencefrost",
"Flamekeeper",
"Essencewrath",
"Nightscar",
"Heartveil",
"Bloodbrand",
"Essencewhisper",
"Grimforge",
"Essencevow",
"Fleshveil",
"Essencestalker",
"Shadowforged",
"Essencegale",
"Mindforged",
"Essenceshade",
"Dreadborn",
"Essencetorn",
"Spiritforge",
"Essencecall",
"Bloodfaith",
"Essenceecho",
"Starwalker",
"Essencegrip",
"Fireborne",
"Essencecoil",
"Dreamdrinker",
"Essencepulse",
"Moonwrought",
"Essencehollow",
"Essencehunger",
"Essencefate",
"Essenceseal",
"Essencefangborn",
"Essenceflarekeeper",
"Essenceflarechain",
"Essencebrim",
"Essencebane",
"Voidforged",
"Spiritflareborn",
"Essencewisp",
"Bloodbound",
"Moonshard",
"Starforged Vanguard",
"Fateflame",
"Dreamshaper",
"Shadowflameborn",
"Sunflare",
"Windwoven",
"Stormtide",
"Heartflare",
"Glassforged",
"Flameveilborn",
"Nightflame",
"Essencebreakerborn",
"Spiritflarechain",
"Boneflare",
"Mindflare",
"Ashflare",
"Frostflare",
"Lightflare",
"Voidflare",
"Starflare",
"Bloodflare",
"Dreamflare",
"Stoneflare",
"Skyflare",
"Moonflare",
"Shadowflare",
"Sunflareborn",
"Essenceforgeborn",
"Spiritforgeborn",
"Flameforgeborn",
"Glassflare",
"Boneflareborn",
"Heartforge",
"Stormflareborn",
"Fateflare",
"Echoflare",
"Windflare",
"Nightflareborn",
"Dreamforgeborn",
"Voidflareborn",
"Essenceflareborn",
"Bloodforgeborn",
"Lightforgeborn",
"Moonflareborn",
"Stoneflareborn",
"Spiritflareborn",
"Starflareborn",
"Sunflarechain",
"Flameflareborn",
"Stormflarechain",
"Veilforged",
"Shadowwrought",
"Essenceborne",
"Frostvein",
"Blightforged",
"Stormveinborn",
"Moonshaper",
"Sunwrought",
"Nightvein",
"Flamewroughtborn",
"Bonecarver",
"Spiritveilborn",
"Starshaper",
"Voidshard",
"Heartvein",
"Glasswrought",
"Windcarver",
"Dreamveil",
"Bloodshaper",
"Lightwrought",
"Ashvein",
"Stonewrought",
"Skyshaper",
"Fatewrought",
"Mindveilborn",
"Emberveinborn",
"Shadowshaper",
"Stormshard",
"Sunforgeborn",
"Moonveilborn",
"Essencemenderborn",
"Spiritshardborn",
"Flamecarverborn",
"Starveilborn",
"Voidwrought",
"Glassveilborn",
"Heartforgeborn",
"Bloodveilborn",
"Dreamforgeborn",
"Nightwrought",
"Boneveilborn",
"Windveil",
"Stoneflareborn",
"Skyveilborn",
"Frostshaper",
"Lightflareborn",
"Emberflareborn",
"Shadowflareborn",
"Sunshaper",
"Moonflareborn",
"Stormforgeborn",
"Spiritflareborn",
"Essenceflareborn",
"Flameflarechain",
"Dreamshardborn",
"Voidflarechain",
"Starflarechain",
"Bloodflarechain",
"Glassflareborn",
"Heartflareborn",
"Frostborn",
"Emberveiled",
"Shadowforged",
"Spiritwoven",
"Nightflare",
"Mooncarver",
"Sunveil",
"Starshard",
"Voidveil",
"Bloodforged",
"Glasscarver",
"Stoneveil",
"Skyforged",
"Windwoven",
"Dreamcarver",
"Heartshard",
"Flameforged",
"Boneflare",
"Essencecarver",
"Stormshaper",
"Lightshard",
"Ashwoven",
"Mindforged",
"Gravecarver",
"Spiritshaper",
"Sunflare",
"Moonforged",
"Starwoven",
"Voidcarver",
"Bloodshard",
"Glassflare",
"Stoneforged",
"Skyshard",
"Windforged",
"Dreamveil",
"Heartwoven",
"Flamecarver",
"Boneforged",
"Essencewoven",
"Stormflare",
"Lightwoven",
"Ashcarver",
"Mindwoven",
"Graveforged",
"Spiritflare",
"Sunshard",
"Moonwoven",
"Starforged",
"Voidflare",
"Bloodwoven",
"Glassshard",
"Stonewoven",
"Skyflare",
"Windshard",
"Dreamforged",
"Heartflare",
"Flamewoven",
"Bonewoven",
"Essenceflare",
"Stormwoven",
"Lightflare",
"Ashforged",
"Mindflare",
"Gravewoven",
"Spiritforged"
];
const ASPECTS = [
  { name: "Shadow Slave", rank: "Divine", description: "You are a miraculous shadow left behind by a dead god. You mourn your former master and long for a new one.", ability: "Shadow Control", abilityDesc: "Your shadow acts independently and obeys you." },
  { name: "Dream Warden", rank: "Transcendent", description: "You guard forgotten dreams, walking between sleep and reality.", ability: "Dream Weave", abilityDesc: "Shape and read others' dreams." },
  { name: "Soulbound Flame", rank: "Ascended", description: "You embody unextinguishable fire, born of passion or vengeance.", ability: "Spiritfire", abilityDesc: "Ignite a target’s spirit to harm body and will." },
  { name: "Eclipse Walker", rank: "Supreme", description: "You move in the space between light and shadow.", ability: "Shadowstep", abilityDesc: "Teleport between shadows instantly." },
  { name: "Blood Oracle", rank: "Sacred", description: "Divine blood flows through you, revealing fates.", ability: "Blood Sight", abilityDesc: "See the lifeforce and predict actions." },
  { name: "Iron Mind", rank: "Awakened", description: "Your mind is an unbreakable fortress.", ability: "Mental Bastion", abilityDesc: "Resist mental attacks and control weak minds." },
  { name: "Voidbound", rank: "Transcendent", description: "A fragment of the void, untouched by the world.", ability: "Nothingness", abilityDesc: "Erase small areas or conceal yourself in shadows." },
  { name: "Starforged", rank: "Divine", description: "Your body and spirit are tempered by cosmic energy.", ability: "Celestial Strike", abilityDesc: "Call down starlight to strike foes." },
  { name: "Whispering Shade", rank: "Ascended", description: "A shadow that speaks in the ears of mortals.", ability: "Mind Whisper", abilityDesc: "Implant suggestions into nearby minds." },
  { name: "Nightbound", rank: "Awakened", description: "You thrive in darkness, gaining power when unseen.", ability: "Dark Affinity", abilityDesc: "Gain strength in shadows." },
  { name: "Soul Reaper", rank: "Ascended", description: "You harvest the souls of the fallen to fuel your power.", ability: "Soul Drain", abilityDesc: "Extract energy from defeated foes." },
  { name: "Frostborn", rank: "Awakened", description: "Cold runs in your veins, freezing what you touch.", ability: "Ice Touch", abilityDesc: "Freeze objects or enemies on contact." },
  { name: "Wind Whisperer", rank: "Transcendent", description: "You command the air and listen to the winds.", ability: "Air Step", abilityDesc: "Move swiftly with the wind." },
  { name: "Blood Pact", rank: "Sacred", description: "Your life and power are linked to another being.", ability: "Life Bond", abilityDesc: "Share strength with a chosen ally." },
  { name: "Spirit Hunter", rank: "Ascended", description: "You sense and hunt spirits across realms.", ability: "Spirit Sense", abilityDesc: "Detect nearby spiritual presences." },
  { name: "Cinderheart", rank: "Transcendent", description: "Your emotions ignite fires that consume.", ability: "Fireburst", abilityDesc: "Release a sudden flame explosion." },
  { name: "Void Warden", rank: "Divine", description: "You guard the thresholds of the void, keeping balance.", ability: "Null Field", abilityDesc: "Suppress magic or energy in an area." },
  { name: "Dream Eater", rank: "Ascended", description: "You consume dreams to gain insight and power.", ability: "Nightmare Feed", abilityDesc: "Weaken targets via their dreams." },
  { name: "Stoneheart", rank: "Awakened", description: "Your body is as resilient as rock itself.", ability: "Earth Armor", abilityDesc: "Increase physical durability." },
  { name: "Moonshadow", rank: "Awakened", description: "You move unseen under moonlight.", ability: "Lunar Veil", abilityDesc: "Become invisible in darkness." },
  { name: "Sunforged", rank: "Ascended", description: "Your body radiates the power of the sun.", ability: "Solar Flare", abilityDesc: "Emit a blinding flash of light." },
  { name: "Stormcaller", rank: "Transcendent", description: "You command storms at will.", ability: "Lightning Strike", abilityDesc: "Summon a bolt of lightning." },
  { name: "Gravebound", rank: "Awakened", description: "The dead heed your call.", ability: "Raise Dead", abilityDesc: "Animate fallen corpses temporarily." },
  { name: "Spiritforged", rank: "Ascended", description: "Your soul strengthens your weapons.", ability: "Soul Weapon", abilityDesc: "Imbue weapons with spiritual power." },
  { name: "Ashborne", rank: "Awakened", description: "You rise from ashes stronger than before.", ability: "Rebirth", abilityDesc: "Recover partially from fatal wounds." },
  { name: "Voidtouched", rank: "Transcendent", description: "You manipulate the void's emptiness.", ability: "Null Strike", abilityDesc: "Erase energy or matter on contact." },
  { name: "Fatebinder", rank: "Sacred", description: "You weave the threads of destiny.", ability: "Bind Fate", abilityDesc: "Limit actions of a chosen target." },
  { name: "Mindweaver", rank: "Ascended", description: "Your mind can manipulate others.", ability: "Mental Pull", abilityDesc: "Influence thoughts directly." },
  { name: "Ironhide", rank: "Awakened", description: "Your skin resists any attack.", ability: "Steel Skin", abilityDesc: "Reduce physical damage taken." },
  { name: "Dreamchaser", rank: "Awakened", description: "You pursue and manipulate dreams.", ability: "Nightmare Step", abilityDesc: "Enter the dreams of others." },
  { name: "Blooddrinker", rank: "Ascended", description: "You gain strength from bloodshed.", ability: "Life Leech", abilityDesc: "Recover health from attacks." },
  { name: "Skystrider", rank: "Transcendent", description: "You move with the freedom of the skies.", ability: "Wind Walk", abilityDesc: "Glide or run through air." },
  { name: "Stonewarden", rank: "Awakened", description: "The earth bends to shield you.", ability: "Earth Shield", abilityDesc: "Create barriers from rock." },
  { name: "Flameheart", rank: "Ascended", description: "Your passion ignites destructive flames.", ability: "Inferno", abilityDesc: "Unleash a wave of fire." },
  { name: "Shadowbinder", rank: "Transcendent", description: "You command shadows to trap foes.", ability: "Bind Shadows", abilityDesc: "Restrict movements with darkness." },
  { name: "Soulwarden", rank: "Sacred", description: "You protect and guide spirits.", ability: "Soul Guard", abilityDesc: "Shield allies from spiritual harm." },
  { name: "Frostvein", rank: "Awakened", description: "Ice flows through your veins.", ability: "Chill Touch", abilityDesc: "Slow or freeze enemies." },
  { name: "Dreamweaver", rank: "Ascended", description: "You craft illusions from dreams.", ability: "Illusive Form", abilityDesc: "Create lifelike illusions." },
  { name: "Voidseer", rank: "Divine", description: "You perceive what others cannot.", ability: "Void Sight", abilityDesc: "See hidden things or portals." },
  { name: "Grimheart", rank: "Ascended", description: "You are relentless and unyielding.", ability: "Iron Will", abilityDesc: "Resist mental attacks." },
  { name: "Nightstalker", rank: "Awakened", description: "You strike unseen under the cover of night.", ability: "Silent Step", abilityDesc: "Move quietly and undetected." },
  { name: "Spiritflame", rank: "Ascended", description: "Your flames burn both body and soul.", ability: "Ethereal Fire", abilityDesc: "Damage spiritual and physical targets." },
  { name: "Sunwarden", rank: "Transcendent", description: "You radiate light to banish darkness.", ability: "Solar Guard", abilityDesc: "Create an area of protective light." },
  { name: "Shadowflare", rank: "Sacred", description: "Dark flames erupt from your being.", ability: "Umbral Fire", abilityDesc: "Damage enemies with shadow fire." },
  { name: "Starflare", rank: "Divine", description: "Celestial fire radiates from you.", ability: "Nova Blast", abilityDesc: "Damage multiple targets." },
  { name: "Voidflare", rank: "Divine", description: "Void ignites with destructive energy.", ability: "Void Blast", abilityDesc: "Extreme area damage with void energy." },
  { name: "Stonepaw", rank: "Dormant", description: "Your hands are as hard as stone.", ability: "Crush", abilityDesc: "Deal extra damage with punches." },
  { name: "Windling", rank: "Dormant", description: "You move lightly and silently.", ability: "Swift Step", abilityDesc: "Move faster and quieter than normal." },
  { name: "Firespark", rank: "Dormant", description: "Small flames dance around you.", ability: "Spark", abilityDesc: "Ignite small fires or flare distractions." },
  { name: "Rootbound", rank: "Awakened", description: "You connect to the earth beneath you.", ability: "Earth Grip", abilityDesc: "Slow enemies by anchoring them." },
  { name: "Gloomling", rank: "Awakened", description: "Shadows gather where you walk.", ability: "Shadow Drift", abilityDesc: "Blend into darkness temporarily." },
  { name: "Stonefist", rank: "Awakened", description: "Your punches carry the weight of boulders.", ability: "Rock Smash", abilityDesc: "Deal crushing damage to objects or enemies." },
  { name: "Frostling", rank: "Awakened", description: "Chill surrounds your body.", ability: "Cold Touch", abilityDesc: "Slow or slightly freeze targets." },
  { name: "Sparkfoot", rank: "Dormant", description: "Your steps leave fleeting sparks.", ability: "Light Dash", abilityDesc: "Move in bursts of speed, dazzling lightly." },
  { name: "Nightpetal", rank: "Dormant", description: "Flowers bloom in your footsteps at night.", ability: "Bloom Step", abilityDesc: "Distract or mislead others with subtle light and fragrance." },
  { name: "Ironblood", rank: "Awakened", description: "Your blood is tougher than normal.", ability: "Resilient", abilityDesc: "Slightly reduce physical damage taken." },
  { name: "Mudborn", rank: "Dormant", description: "You blend with soil and dirt.", ability: "Camouflage", abilityDesc: "Hide effectively in natural terrain." },
  { name: "Ashling", rank: "Awakened", description: "Ash floats around your body.", ability: "Smokescreen", abilityDesc: "Create a temporary cloud of ash to obscure vision." },
  { name: "Pebbleheart", rank: "Dormant", description: "You feel stronger when standing on rocks.", ability: "Sturdy Stance", abilityDesc: "Reduce knockback and maintain balance." },
  { name: "Rainwhisper", rank: "Dormant", description: "You hear secrets carried by the rain.", ability: "Weather Sense", abilityDesc: "Detect distant events in rainy conditions." },
  { name: "Leafstep", rank: "Awakened", description: "You tread without leaving marks.", ability: "Silent Walk", abilityDesc: "Move silently on any terrain." },
  { name: "Glowmite", rank: "Dormant", description: "Tiny lights hover around you.", ability: "Flicker", abilityDesc: "Create minor distractions with small glowing lights." },
  { name: "Barkskin", rank: "Awakened", description: "Your skin hardens like tree bark.", ability: "Natural Armor", abilityDesc: "Reduce light physical damage." },
  { name: "Driftling", rank: "Dormant", description: "You float lightly with the wind.", ability: "Float", abilityDesc: "Move slightly above the ground, avoiding small obstacles." },
  { name: "Mudveil", rank: "Awakened", description: "You hide within mud and dirt easily.", ability: "Conceal", abilityDesc: "Blend with terrain to avoid detection." },
  { name: "Frostbud", rank: "Dormant", description: "A small frost forms around you.", ability: "Chill Aura", abilityDesc: "Cool nearby air and slow small creatures slightly." },
  { name: "provoker", rank: "Ascended", description: "Conflict follows you not because you seek it, but because the world stirs when you walk through it. People react sharply around you — tempers flare, pride rises, and old grudges wake at your presence. You were never meant for quiet paths. Your fate is to trigger movement in stagnant places, to push others into choices they’ve avoided, and to stand at the center of storms you never asked for.", ability: "Fury Harvest", abilityDesc: "When the enemies is in max rage or they're provocked long enough There strength will be drained, physical and soul essence And those energy will go to you" },

];


async function generateTrueName() {
  let rand = Math.floor(Math.random()* TrueNames.length)
  return TrueNames[rand]
}

function getAttributeCount() {
  const r = Math.random();
  if (r < 0.6) return 1;     
  if (r < 0.7) return 2;    
  if (r < 0.98) return 3;    
  return 4;                  
}
function getRandomAttributes() {
  const count = getAttributeCount();
  const shuffled = [...Attributes].sort(() => 0.5 - Math.random());
  return shuffled.slice(0, count);
}

const attributes = getRandomAttributes();
const attributeText = attributes.map(a => `[${a}]`).join(", ");


function getRank() {
  const r = Math.random();
  if (r < 0.5) return "Dormant";     
  if (r < 0.6) return "Awakened" ;    
  if (r < 0.8) return "Ascended";    
  if (r < 0.9) return "Transcendent";
  if (r < 0.99) return "Supreme";
  if (r < 0.999) return "Sacred";
  if (r < 0.99999) return "Divine";
}

function getRandomAspectByRank(rank) {
  const filtered = ASPECTS.filter(a => a.rank === rank);
  if (filtered.length === 0) return null; 
  const randIndex = Math.floor(Math.random() * filtered.length);
  return filtered[randIndex];
}

function generateflaw() {
  let rand = Math.floor(Math.random()* Flaws.length)
  return Flaws[rand]
}

let aspect = getRandomAspectByRank(getRank())
let flaw = generateflaw()

  const textBlocks = [
    `Name: ${name}.`,
    `True Name: ${await generateTrueName()}.`,
    "Rank: Dreamer.",
    "Soul Core: Dormant.",
    "",
    `Soul Fragments: ${Math.floor(Math.random() * 1000)}/1000`,
    "",
    "Memories: —",
    "Echoes: —",
    `Attributes: ${attributeText}.`,
    "",
    `Aspect: [${aspect.name}].`,
    `Aspect Rank: ${aspect.rank}.`,
    `Aspect Description: [${aspect.description}]`,
    "",
    `Aspect Ability: [${aspect.ability}].`,
    `Aspect Ability Description: [${aspect.abilityDesc}]`,
    "",
    `Flaw: [${flaw.name}].`,
    `Flaw Description: [${flaw.desc}]`
  ];

  async function typeLine(line, delay = 15) {
    const p = document.createElement("p");
    result.appendChild(p);

    for (let i = 0; i < line.length; i++) {
      const span = document.createElement("span");
      span.textContent = line[i] === " " ? "\u00A0" : line[i];
      span.classList.add("glow-text");
      span.style.setProperty("--delay", `${i * 0.03}s`);
      p.appendChild(span);

      await new Promise(r => setTimeout(r, delay));
      window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" });
    }

    await new Promise(r => setTimeout(r, 300));
  }

  // Disable the button while typing
  document.getElementById("generate").disabled = true;

  for (const line of textBlocks) {
    await typeLine(line);
  }

  document.getElementById("generate").disabled = false;

   await new Promise(resolve => setTimeout(resolve, 1500));

  button.textContent = "Generate Again";
  button.classList.remove("fade-out");
  button.classList.add("fade-in-under");
  button.style.display = "block";
  result.insertAdjacentElement("afterend", button);

  button.onclick = () => location.reload();

  // Re-enable button
  button.disabled = false;
  button.style.pointerEvents = "auto";

  window.scrollTo({ top: document.body.scrollHeight, behavior: 'smooth' });
}


